CrisisCleanup/crisiscleanup-2

app/assets/stylesheets/static_pages.scss
app/views/layouts/application.html.erb
app/views/layouts/menus/_application_menu.html.erb
app/views/static_pages/index.html.erb

7.1 Design public content layout (i.e. ⅔ / ⅓ layout)
9.1 Design public sidebar (exposition + call to action buttons)
12. Identify and import lean slider for homepage
10.1 create core template for public
3.2 Identify theme colors

Design home page (second draft): content layout, slider, colors, core template

---

Gemfile
Gemfile.lock
app/controllers/admin/legacy_contacts_controller.rb
app/controllers/admin/legacy_events_controller.rb
app/controllers/admin/legacy_organizations_controller.rb
app/controllers/admin/legacy_sites_controller.rb
app/views/admin/legacy_contacts/index.html.erb
app/views/admin/legacy_events/index.html.erb
app/views/admin/legacy_organizations/index.html.erb
app/views/admin/legacy_sites/index.html.erb

Pagination complete

---

Gemfile
Gemfile.lock
app/assets/javascripts/scripts.js
app/controllers/admin/legacy_contacts_controller.rb
app/controllers/admin/legacy_events_controller.rb
app/controllers/admin/legacy_organizations_controller.rb
app/helpers/application_helper.rb
app/models/legacy/legacy_contact.rb
app/models/legacy/legacy_event.rb
app/models/legacy/legacy_organization.rb
app/models/legacy/legacy_site.rb
app/views/admin/legacy_contacts/_versions.html.erb
app/views/admin/legacy_contacts/edit.html.erb
app/views/admin/legacy_events/_versions.html.erb
app/views/admin/legacy_events/edit.html.erb
app/views/admin/legacy_organizations/_versions.html.erb
app/views/admin/legacy_organizations/edit.html.erb
app/views/admin/legacy_sites/_versions.html.erb
app/views/admin/legacy_sites/edit.html.erb
db/migrate/20150715161736_create_versions.rb
db/schema.rb

- all four legacy models have auditing
- each model's edit page on /admin has a previous versions tab, that shows all previous versions

Paper Trail auditing gem

---

app/controllers/admin/dashboard_controller.rb
app/models/legacy/legacy_organization.rb
app/models/legacy/legacy_site.rb

- removed unecessary validations on legacy_organization
- more robust before_validations on legacy_site

fixed admin bugs

---

app/controllers/admin/legacy_organizations_controller.rb
app/controllers/admin/users_controller.rb
app/mailers/admin_mailer.rb
app/views/admin/legacy_contacts/_table.html.erb
app/views/admin/legacy_organizations/edit.html.erb
app/views/admin/legacy_organizations/index.html.erb

- add contacts as tab on org profile
- include phone number on contact index
- admin edit contact validate last name
- create new org doesn't work?
- email notification new user
- set title on all admin pages
- org index filters

Admin bugs

---

app/helpers/application_helper.rb
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_worker_dashboard_menu.html.erb
config/routes.rb

I did some code formatting here and there, but I tried to avoid that for the most part. I also didn't do anything with the worker current event links in the worker nav. I'm not sure how those will be handled since they currently all link to legacy paths.

Create nav_link helper to add an active class to the current page's nav

---

app/assets/stylesheets/public_pages/_static_pages.scss
app/views/registrations/_legacy_contact_form.html.erb
app/views/registrations/_registration_form.html.erb
app/views/static_pages/public_map.html.erb
app/views/worker/incident/legacy_sites/map.html.erb

Fixed /register layout and public_map sidebar content

/register + public_map design edits

---

app/helpers/application_helper.rb
app/models/legacy/legacy_organization.rb
app/views/admin/stats/by_incident.csv.erb
app/views/admin/stats/by_incident.html.erb
app/views/worker/incident/legacy_sites/stats.html.erb

This also cleans up a merge conflict in the stats.csv.erb.

Move helpers into org model and update 3 views that use them

---

app/controllers/worker/incident/legacy_organizations_controller.rb

https://www.pivotaltracker.com/story/show/100168004

Filter out unverified orgs in the worker incident view.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/incident_pages/_map.scss
app/assets/stylesheets/modules/_buttons.scss

HTML FORM SENT SEPARATELY
Notes on Texas Form
- Use h4’s to act as form section titles and h5’s for form section subtitles
- Checkbox div columns
- div class=“small-11 medium-11 large-11 columns” for labels
- div class=“small-1 medium-1 large-1 columns” for checkboxes
- We will need to test ranged slider. I set it up using the code documented here (http://foundation.zurb.com/sites/docs/v/5.5.3/components/range_slider.html) to go in increments of 1 up to 5. We need to be sure that the data classes are synced up correctly with the db.
- Labels should not have the same classes as inputs
- Labels will 99% of the time remain the same, and should remain simple. The only thing that should be consistent in this regard is <label for=“insert name of input here”>.
- Replicating the input classes on …

Add styles for advanced incident form features. Styles connect with Texas disaster

---

app/views/static_pages/government.html.erb
app/views/static_pages/survivor.html.erb
app/views/static_pages/voad.html.erb
app/views/static_pages/volunteer.html.erb
config/routes.rb

This is pretty straight forward, but I'm not sure if we want to update the content on master or in this branch.

Static audience landing pages

---

app/assets/javascripts/models/filter.js
app/assets/javascripts/models/map.js
db/schema.rb

Add filter for pins that are not Debris, Flood, or Trees
Remove Goods and services filter
I'm not sure this addresses the initial state error. Also, check out the db/schema.rb update. I think some things may be off either in the repo or the heroku db.

Remove the map zoom on filter select.

---

app/assets/javascripts/models/map.js
app/assets/javascripts/models/marker.js
app/assets/javascripts/static_pages/public_map.js
app/controllers/api/public/json_controller.rb
app/views/static_pages/public_map.html.erb

This just gets the public map markers working again and adds an infobox. We need to style the box and maybe add buttons? I'm not sure how the buttons work differently on the public map.

Fix the public map and add a public infobox

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_nav_dropdown_mobile.scss
app/views/layouts/menus/_alert_menu.html.erb

fixed mobile nav bug with nested lists not showing
edited alert_box design
added alert boxes

Nav + Alert_Box Updates (Re: Design Punchlist)

---

app/views/layouts/menus/_admin_dashboard_menu.html.erb
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_worker_dashboard_menu.html.erb

@andygimma @zenjyn 
- I need a code review for this feature.
- I don't think we're using map_menu.html anymore. Double checking before possible deletion.
--> We need to discuss merging all navigation templates into one file...I don't think we need 4 files

add user status indication feature

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/incident_pages/_map.scss
app/assets/stylesheets/public_pages/_static_pages.scss
app/controllers/static_pages_controller.rb
app/views/layouts/menus/_admin_dashboard_menu.html.erb
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_map_menu.html.erb
app/views/layouts/menus/_worker_dashboard_menu.html.erb
app/views/static_pages/about.html.erb
app/views/static_pages/government.html.erb
app/views/static_pages/survivor.html.erb
app/views/static_pages/voad.html.erb
app/views/static_pages/volunteer.html.erb
app/views/worker/incident/legacy_sites/form.html.erb
app/views/worker/incident/legacy_sites/map.html.erb

- Edits to /voad, /government, /survivor, /volunteer
- Design punchlist items
- General design cleanup / adjustments
- @aarontitus please refer to pivotal tracker comments for Design Punchlist card...some of those items that are marked as complete are complete from my end only and will require some adjustments on things  you control.

design punchlist items, new static pages --> sidebar template

---

app/views/devise/sessions/new_demo.html.erb
app/views/layouts/menus/_alert_menu_demo.html.erb
app/views/static_pages/about.html.erb
app/views/static_pages/index_demo.html.erb
app/views/static_pages/new_incident_demo.html.erb
app/views/static_pages/privacy.html.erb
app/views/static_pages/signup.html.erb
app/views/static_pages/survivor.html.erb
app/views/worker/dashboard/redeploy_form.html.erb

Related to https://www.pivotaltracker.com/story/show/115272821

Content update; New Demo Content

---

app/views/invitation_mailer/send_confirmation_alert.html.erb
app/views/invitation_mailer/send_invitation.html.erb
app/views/registrations/new.html.erb
app/views/registrations/welcome.html.erb
app/views/static_pages/about.html.erb
app/views/worker/incident/legacy_sites/print.html.erb

Updated Printer Friendly version, which had many incorrect or missing
fields.

Update Printer Friendly Version

---

app/views/worker/incident/legacy_sites/print.html.erb

Assigned correct model for work_requested

Update Printer Friendly

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/incident_pages/_map.scss
app/views/worker/incident/legacy_sites/form.html.erb
app/views/worker/incident/legacy_sites/map.html.erb

/map and /form map-canvas fixes for desktop and mobile

---

app/assets/javascripts/models/map.js
app/assets/javascripts/models/marker.js
app/controllers/api/json_controller.rb
app/controllers/api/public/json_controller.rb
app/views/api/json/map.rabl
app/views/api/public/json/map.rabl
app/views/worker/incident/legacy_sites/_site_form.html.erb
config/routes.rb

Update the map to load with a minimal set of data. Fetch full data on

---

app/controllers/api/json_controller.rb
app/models/legacy/legacy_site.rb
app/views/api/json/map.rabl

Also updates the site duplicate detection.

Fix the map sites query and the site duplicate detection.

---

app/assets/javascripts/models/map.js

Added a geocode query event to the city, state, and zip fields for a new

---

app/mailers/invitation_mailer.rb
app/views/devise/sessions/new.html.erb
app/views/invitation_mailer/send_invitation.html.erb
spec/mailers/invitation_mailer_spec.rb

Also included an update to login instructions.

Revert Invitation Mailer for Normal Use

---

app/assets/javascripts/models/form.js
app/assets/javascripts/models/map.js
app/assets/javascripts/scripts.js
app/assets/stylesheets/incident_pages/_map.scss
app/controllers/api/json_controller.rb
app/controllers/api/public/json_controller.rb
app/controllers/worker/incident/legacy_sites_controller.rb
app/models/legacy/legacy_site.rb
app/views/worker/incident/legacy_sites/map.html.erb
config/routes.rb

Add address to the case number in the link
Zoom to the marker on the map page and open the infobox

Add list of links to potential duplicate sites

---

app/assets/javascripts/models/marker.js
app/controllers/worker/incident/legacy_sites_controller.rb
config/routes.rb

Fix the infobox close button placement.

Fix the print link to use the event id for permissions.

---

app/controllers/worker/incident/legacy_sites_controller.rb
app/views/worker/incident/legacy_sites/stats.html.erb

Get the correct organizations for the event.

---

app/assets/stylesheets/incident_pages/_map.scss
app/assets/stylesheets/public_pages/_static_pages.scss
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_map_menu.html.erb
app/views/layouts/menus/_worker_dashboard_menu.html.erb
app/views/layouts/worker_dashboard.html.erb
app/views/worker/incident/legacy_sites/_site_form.html.erb
app/views/worker/incident/legacy_sites/map.html.erb

- ie logo bug 
-google suggest address wrap
- splash page image fix for high-res screens 
- /form buttons
- Attempt #1 to get pac-container right

4.13.16 Bug Fixes

---

app/views/devise/sessions/new.html.erb
app/views/invitation_mailer/send_invitation.html.erb
app/views/layouts/menus/_alert_menu_demo.html.erb
app/views/static_pages/about.html.erb

Messaging Update

---

app/assets/javascripts/models/map.js

including
Hours Worked Per Volunteer
Initials of Resident Present
Total Volunteers
Status Notes

Add headers and populate fields for legacy site csv downloads

---

app/models/legacy/legacy_site.rb

I ran this code on Hurricane Matthew, and all seemed to go well.

Implement the Details column in the CSV download

---

app/models/legacy/legacy_site.rb

Add a nil check to the details column

---

app/views/layouts/admin_dashboard.html.erb
app/views/layouts/application.html.erb
app/views/layouts/application_sidebar.html.erb
app/views/layouts/worker_dashboard.html.erb

So that I can comment out the correct footer

Add comment identifiers to footers

---

app/assets/stylesheets/modules/_typography.scss
app/views/layouts/menus/_admin_dashboard_menu.html.erb
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_map_menu.html.erb
app/views/static_pages/index.html.erb
app/views/static_pages/survivor.html.erb
app/views/worker/dashboard/index.html.erb

Update Links, Formatting

---

app/controllers/worker/incident/legacy_sites_controller.rb
app/views/worker/incident/legacy_sites/index.html.erb
app/views/worker/incident/legacy_sites/map.html.erb
app/views/worker/incident/legacy_sites/mysites.html.erb

crisiscleanup-302 Map > History > Claimed By email address link nil.

---

app/views/layouts/menus/_alert_menu.html.erb

Alert update

---

app/assets/javascripts/components/dashboard.js
app/controllers/api/json_controller.rb
app/views/worker/dashboard/index.html.erb

Dashboard dynamic site status

---

app/controllers/worker/incident/legacy_sites_controller.rb

crisiscleanup-299 Save and Claim not pulling to dashboard

---

app/assets/javascripts/models/marker.js

Created newlines for case number, phone1 (if present), and phone 2 (if present).  Happy to have any feedback with this.  I'd still like to format the details a bit more but they could be in a separate pull request if needed.

Initial take on issue 343 - linking phone numbers

---

app/assets/javascripts/models/marker.js

Made the phone numbers themselves into text elements to get rid of the error with the original pull request.

Updated code with fix included

---

app/controllers/worker/incident/legacy_contacts_controller.rb
app/helpers/application_helper.rb
app/javascript/legacy/other/organization_contacts.js
app/javascript/packs/application.js
app/views/worker/incident/legacy_contacts/_legacy_contact_form.html.erb
app/views/worker/incident/legacy_contacts/edit.html.erb
app/views/worker/incident/legacy_contacts/index.html.erb
config/environments/development.rb
config/routes.rb

Add form to allow organization members to update the contacts of their organization

---

app/controllers/worker/dashboard_controller.rb
app/views/layouts/menus/_application_menu.html.erb
app/views/layouts/menus/_worker_dashboard_menu.html.erb

Check if a redeploy request was already completed for an incident.  Add flash message to alert user.

Check for completed redeploy request
